### ISSUE TITLE
How do I stop it from accidentally making videos bigger?

### ISSUE THREAD

**Issue by broiswear** [kachurovskiy/batchviproc#1]
I ran this on a certain folder overnight. The end result was that it stopped when my PC ran out of disk space. I looked at the log, and on multiple videos, the compressed file came out larger. And indeed, when I compared the folder sizes, it doubled from circa 30GB to like 68GB, and it didn't even manage to go through everything yet.

Does anyone know how to undo the enlargings and how to prevent them from occurring? I REALLY need to undo the enlargings, considering that this software managed to hit my PC's storage limit.

**Comment by kachurovskiy** [comment]
@broiswear you can sort files in your folder by creation date, find files created during the run and delete them.

The app doesn't know ahead of the time if the re-encoded version is going to end up smaller. It usually does - but not always, depends on how much movement there is in the video. Fixed camera videos e.g. security camera recordings compress the best.

As you can see in https://github.com/kachurovskiy/batchviproc/blob/main/app/main.js#L120 currently when the output file is larger, we just move on and don't delete the newly created file. Perhaps it would make sense to delete it right away.

**Comment by kachurovskiy** [comment]
@broiswear the temporary files are created in the same folder you chose when starting the app. Currently there's a bug that if the output file is larger than original, it's not deleted. You can identify those files by filename - they have `.tmp.` in their name e.g. `PXL_20240218_131121171.tmp.mp4`

You can simply use the upper-right "Search in current folder" feature to find all these files and then select them all and delete permanently via `Shift-Del` so that they don't take space in Recycle Bin.

**Comment by broiswear** [comment]
Ok, thanks for the info.
